config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  get 'parti2022', to: 'pages#parti2022'
  get 'home_what_we_do', to: 'pages#home_what_we_do'
  get 'what_we_do', to: 'pages#what_we_do'
  get 'marketing', to: 'pages#marketing'
  get 'camp', to: 'pages#camp'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_revisions/v1', to: 'pages#privacy_revisions_v1', as: :privacy_revisions_v1
  Solution::DICTIONARY.each do |solution_slug,_|
    get "solutions/#{solution_slug}", to: "solutions##{solution_slug}", as: :"solutions_#{solution_slug}"
  end
  get 'solutions/soft', to: 'solutions#soft', as: :solutions_soft
  post 'reports/subscribe', to: 'pages#subscribe_reports', as: :subscribe_reports

  resources :contacts
  resources :posts, only: :show

  post 'attachments', to: 'attachments#create'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/views/pages/home/what_we_do/_category_filters.html.haml
.categories.js-post-tiles-filter
  .category{ class: ('active' if params[:category_slug].blank?) }
    = link_to home_what_we_do_path(category_slug: nil, format: :js), remote: true, class: 'category-text' do
      전체
  - Post::CATEGORIES.each do |category_slug, category_title|
    .category{ class: ('active' if category_slug.to_s == params[:category_slug]) }
      = link_to home_what_we_do_path(category_slug: category_slug, format: :js), remote: true, class: 'category-text' do
        != category_title

app/views/pages/home/what_we_do/_posts.html.haml
.tiles-container.js-post-tiles-container
  - if posts.empty?
    %p.lead.text-center.w-100
      글을 준비 중입니다.
  - else
    - post = posts.first
    .tiles-column.js-sticky-sidebar
      .tile-container.tile-container-lg
        = link_to post do
          .tile
            .tile-meta
              .category!= post.category_title
              .title!= post.title
              .created-at= static_day_f(post.published_at)
            .tile-cover-container
              .tile-cover{ style: "background-image: linear-gradient(to bottom, #11111100, #11111133), url(#{post.cover_url})" }

    .tiles-column<>
      - posts[1..-1].each do |post|
        .tile-container.tile-container-sm<>
          = link_to post do
            .tile
              .tile-cover-container
                .tile-cover{ style: "background-image: url(#{post.cover_url})" }
              .tile-meta
                .category!= post.category_title
                .title!= post.title
                .created-at= static_day_f(post.published_at)
      .tile-more.text-center
        = link_to what_we_do_path(category_slug: category_slug), class: 'btn btn-outline-primary btn-more' do
          더 보기