config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  get 'parti2022', to: 'pages#parti2022'
  get 'home_what_we_do', to: 'pages#home_what_we_do'
  get 'what_we_do', to: 'pages#what_we_do'
  get 'marketing', to: 'pages#marketing'
  get 'camp', to: 'pages#camp'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_revisions/v1', to: 'pages#privacy_revisions_v1', as: :privacy_revisions_v1
  Solution::DICTIONARY.each do |solution_slug,_|
    get "solutions/#{solution_slug}", to: "solutions##{solution_slug}", as: :"solutions_#{solution_slug}"
  end
  get 'solutions/soft', to: 'solutions#soft', as: :solutions_soft
  post 'reports/subscribe', to: 'pages#subscribe_reports', as: :subscribe_reports

  resources :contacts
  resources :posts, only: :show

  post 'attachments', to: 'attachments#create'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :project_subject, presence: true
  validates :project_body, presence: true
  validates :project_why, presence: true
  validates :contact_email, presence: true
  mount_uploader :attachment, DocumentUploader

  serialize :solution_slugs, JSON

  scope :solution_slugs_array_in, ->(*some_solution_slugs) {
    result = self.none

    some_solution_slugs.map { |some_solution_slug| "%#{some_solution_slug}%" }.each do |like_solution_slug|
      result = result.or(self.where("solution_slugs like ?", like_solution_slug))
    end

    return result
  }

  before_save :trim_solution_slugs

  SOLUTION_OPTIONS = Solution::DICTIONARY.map do |solution_slug, solution_info|
    {
      title: solution_info[:title],
      slug: solution_slug
    }
  end + [
    {
      title: Platform::INFO[:title],
      slug: Platform::INFO[:slug],
    }
  ] + [
    {
      title: '기타',
      slug: 'etc'
    }
  ]

  def self.ransackable_scopes(auth_object = nil)
    %i(solution_slugs_array_in)
  end

  private

  def trim_solution_slugs
    self.solution_slugs.reject! { |c| c.empty? }
  end
end

app/controllers/contacts_controller.rb
require 'slack-notifier'

class ContactsController < ApplicationController
  def new
    @contact = Contact.new

    prepare_meta_tags(title: '협업 문의', description: '활동 영역 별 다양한 방식으로 여러분과 협업합니다.', url: new_contact_url)
  end

  def create
    @contact = Contact.new(contact_params)

    if !NewGoogleRecaptcha.human?(
      params[:new_google_recaptcha_token],
      "checkout",
      NewGoogleRecaptcha.minimum_score,
      @contact
    ) || !@contact.save
      errors_to_flash(@contact)
      render 'new' and return
    end

    append_flash_message(:success, '협업 요청해 주셔서 감사합니다. 검토 후 빠른 시일 내로 연락드리겠습니다.')
    redirect_to root_url

    if @contact.confirm_mailing?
      outcome = MailingSubscribe.run(name: @contact.contact_manager, email: @contact.contact_email)
      if outcome.valid?
        append_flash_message(:success, '민주주의 리포트 구독 확인 이메일을 발송했습니다. 보내드린 이메일을 확인하면 구독이 완료됩니다.')
      else
        messages = outcome.errors.full_messages.join('. ')
        logger.error messages
        if outcome.errors.added?(:base, :server)
          flash[:error] = messages
        else
          flash[:error] = '민주주의 리포트 구독이 실패했습니다. contact@parti.coop로 구독 신청 메일을 보내 주세요.'
        end
      end
    end

    begin
      notifier = Slack::Notifier.new ENV["SLACK_DOCKING"]
      notifier.post username: '휴스턴 관제센터',
        attachments:
          [
            {
              color: "good",
              text: "[도킹 요청] #{@contact.solution_slugs.join(', ')}",
              fields:
                %i(project_subject project_body project_why
                attachment_name attachment_url
                contact_org contact_manager
                contact_tel contact_email).map do |attr|
                  {
                    "title": Contact.human_attribute_name(attr),
                    "value": @contact.send(attr),
                    "short": false
                  }
                end
            }
          ]
    rescue
    end

    begin
      ContactMailer.with(contact: @contact).new_contact.deliver_later
    rescue
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:project_subject, :project_body, :project_why, :attachment, :contact_org, :contact_manager, :contact_tel, :contact_email, :confirm_privacy, :confirm_marketing, :confirm_mailing, solution_slugs: [])
  end

  def append_flash_message(type, msg)
    flash[type] ||= []
    flash[type] << msg
  end
end

app/views/contacts/new.html.haml
%section.key-visual
  .container.container-xs
    .title-container
      .page-title
        협업 문의
      .page-subtitle.text-keep-all
        활동 영역 별 다양한 방식으로 여러분과 협업합니다.

= content_for :recaptcha_js do
  = include_recaptcha_js

%section.form
  .container.container-xs
    = form_with model: @contact, local: true, id: 'js-contact-form', class: 'js-form-validation' do |f|
      %fieldset
        %legend 프로젝트 정보

        .alert.alert-secondary.help-text
          * 는 필수 입력 항목입니다.

        .form-group
          = f.label :project_subject
          = f.text_field :project_subject, class: 'form-control', data: { 'rule-required': true }, maxlength: 255
        .form-group
          = f.label :project_body
          = f.text_area :project_body, class: 'form-control', placeholder: '프로젝트 소개, 기간, 예산', data: { 'rule-required': true }, maxlength: 20000
        .form-group
          = f.label :project_why
          = f.text_area :project_why, class: 'form-control', placeholder: '빠띠를 어떻게 알게 되셨나요? 왜 빠띠인지 조금만 더 설명해주시면 효과적으로 접수를 진행할 수 있어요.', data: { 'rule-required': true }, maxlength: 20000
        .form-group
          = f.label :solution_slugs
          - Contact::SOLUTION_OPTIONS.each do |solution_option|
            .form-check
              = f.check_box :solution_slugs, { class: 'form-check-input -solution form-control', multiple: true }, solution_option[:slug], nil
              %label.form-check-label{ for: "contact_solution_slugs_#{solution_option[:slug]}" }<>
                = solution_option[:title]
        .form-group
          = f.label :attachment
          = f.file_field :attachment, class: 'form-control'
      %fieldset
        %legend 연락처
        .form-group
          = f.label :contact_org
          = f.text_field :contact_org, class: 'form-control', maxlength: 255
        .form-group
          = f.label :contact_manager
          = f.text_field :contact_manager, class: 'form-control', data: { 'rule-required': true }, maxlength: 255
        .form-group
          = f.label :contact_tel
          = f.text_field :contact_tel, class: 'form-control', maxlength: 255
        .form-group
          = f.label :contact_email
          = f.email_field :contact_email, class: 'form-control', data: { 'rule-required': true }, maxlength: 255

        .form-group
          .form-check
            = f.check_box :confirm_all, class: 'form-check-input js-confirm-all', id: 'contact_confirm_all'
            %label.form-check-label{ for: 'contact_confirm_all' }<>
              %span<> 개인정보 수집 및 처리,&nbsp;
              %span<> 마케팅 정보 수신(선택),&nbsp;
              %span<> 민주주의 리포트 구독(선택)
              에 모두 동의합니다.
          .ml-4
            .form-check
              = f.check_box :confirm_privacy, class: 'form-check-input js-confirm-all-target', data: { 'rule-required': true, 'invalid-error': '#js-contact-checkbox-error', msg: '개인정보 수집 및 처리 동의가 필요합니다.' }
              %label.form-check-label{ for: 'contact_confirm_privacy' }<>
                = link_to '개인정보 수집 및 처리', privacy_path, target: '_blank', style: 'text-decoration: underline'
                에 동의합니다.
            #js-contact-checkbox-error


            .form-check
              = f.check_box :confirm_marketing, class: 'form-check-input js-confirm-all-target'
              %label.form-check-label{ for: 'contact_confirm_marketing' }<>
                = link_to '마케팅 정보 수신', marketing_path, target: '_blank', style: 'text-decoration: underline'
                에 동의합니다. (선택)
              .form-text
                빠띠가 진행하는 여러 이벤트의 알림을 받으시고 혜택을 놓치지 마세요.

            .form-check
              = f.check_box :confirm_mailing, class: 'form-check-input js-confirm-all-target'
              %label.form-check-label{ for: 'contact_confirm_mailing' }<>
                민주주의 리포트를 구독합니다. (선택)
              .form-text
                빠띠의 민주주의 리포트를 매월 이메일로 받아보세요.

        = recaptcha_action('checkout')

        = f.submit '협업문의하기', class: 'btn btn-primary btn-block'