config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  get 'parti2022', to: 'pages#parti2022'
  get 'home_what_we_do', to: 'pages#home_what_we_do'
  get 'what_we_do', to: 'pages#what_we_do'
  get 'marketing', to: 'pages#marketing'
  get 'camp', to: 'pages#camp'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_revisions/v1', to: 'pages#privacy_revisions_v1', as: :privacy_revisions_v1
  Solution::DICTIONARY.each do |solution_slug,_|
    get "solutions/#{solution_slug}", to: "solutions##{solution_slug}", as: :"solutions_#{solution_slug}"
  end
  get 'solutions/soft', to: 'solutions#soft', as: :solutions_soft
  post 'reports/subscribe', to: 'pages#subscribe_reports', as: :subscribe_reports

  resources :contacts
  resources :posts, only: :show

  post 'attachments', to: 'attachments#create'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :prepare_meta_tags, if: -> { request.get? }

  def errors_to_flash(model)
    flash[:error] = errors_to_str(model, '<br>').html_safe
  end

  def errors_to_str(model, br)
    return if model.errors.empty?
    result ||= ""
    result += model.errors.full_messages.join(br)
    result
  end

  def prepare_meta_tags(options={})
    set_meta_tags build_meta_options(options)
  end

  def build_meta_options(options)
    site_name = "사회적협동조합 빠띠"
    title = ( options[:title].present? ? "#{view_context.strip_tags(options[:title])} | 빠띠" : "사회적협동조합 빠띠" )
    image = options[:image] || view_context.image_url('parti-ci.png')
    url = options[:url] || root_url
    description = view_context.strip_tags(options[:description]) || "빠띠는 민주주의를 혁신하고 사회의 여러 영역으로 확산하기 위해 툴킷, 플랫폼, 커뮤니티를 만드는 민주주의 활동가들의 협동조합입니다."
    {
      title:       title,
      reverse:     true,
      image:       image,
      description: description,
      keywords:    "사회적협동조합, 커뮤니티, 캠페인, 민주주의 개발, 공익 데이터, 민주주의 랩, 플랫폼, 협동조합, 빠띠, 우주당, 시민참여플랫폼, 민주주의 툴킷, 민주주의 캠페인, 정치참여, 정치, 민주주의, it, 툴킷, 정치캠페인, 더나은민주주의, digital democracy, 시민, 직접민주주의, 일상의 민주주의, 공공재, 공론장, 숙의민주주의",
      canonical:   url,
      twitter: {
        site_name: site_name,
        site: '@parti_coop',
        card: 'summary',
        title: title,
        description: description,
        image: image
      },
      og: {
        url: url,
        site_name: site_name,
        title: title,
        image: image,
        description: description,
        type: 'website'
      }
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    dasherized_controller_name = params[:controller].gsub(/\//, '--')
    arr = ["body-#{dasherized_controller_name}", "body-#{dasherized_controller_name}-#{params[:action]}"]
    arr.join(' ')
  end

  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'bg-success'
    when 'error'
      'bg-danger'
    when 'alert'
      'bg-warning'
    when 'notice'
      'bg-info'
    else
      flash_type.to_s
    end
  end

  def i18n_for_flash(flash_type)
    case flash_type
    when 'success'
      '성공'
    when 'error'
      '오류'
    when 'alert'
      '경고'
    when 'notice'
      '안내'
    else
      flash_type.to_s
    end
  end

  def static_day_f(date)
    date.strftime("%Y.%m.%d")
  end

  def excerpt(text, options = {})
    return text if text.blank?

    options[:length] = 130 unless options.has_key?(:length)
    result = strip_tags(text)
    return result if result.blank?

    result = HTMLEntities.new.decode(result)
    return result.truncate(options[:length], options)
  end

  def is_kakao_talkable?
    browser.device.mobile?
  end
end

app/views/application/_flash.html.haml
%div.position-fixed.d-flex.flex-column.p-4#site-flashs-top{ "aria-atomic": "true", "aria-live": "polite", "data-autohide": "false", "style": "z-index: 1; right: 0;" }
  - flash.each do |type, msg|
    = render 'application/flash_item', type: type, msg: msg
- flash.discard
%div.position-fixed.d-flex.flex-column.p-4#site-flashs-bottom{ "aria-atomic": "true", "aria-live": "polite", "data-autohide": "false", "style": "z-index: 1; bottom: 0; right: 0;" }

app/views/application/_flash_item.html.haml
- msg = [msg] unless msg.respond_to?(:each)
- msg.each do |msg_item|
  .toast.ml-auto.js-toast{ role: 'alert', "data-delay": "300000" }
    .toast-header.text-white{ class: bootstrap_class_for_flash(type) }
      %strong.mr-auto= i18n_for_flash(type)
      %button.ml-2.mb-1.close{ "aria-label": "Close", "data-dismiss": "toast", type: "button" }
        %span.text-white{ "aria-hidden": "true" }
          &times;
    .toast-body
      = msg_item

app/views/application/_footer.html.haml
- if controller_name != 'contacts'
  %section.contacts
    .container.container-sm
      .base-section-title
        빠띠와 협업하기
      .base-section-desc.text-keep-all
        -# 다양한 방식으로 여러분과 협업합니다.
        프로젝트, 컨설팅, 교육,
        %span.text-nowrap 디지털 솔루션까지
        %br
        다양한 방식으로 여러분과
        %span.text-nowrap 함께 합니다.

        -# %br
        -# .text-nowrap
        -#   지금 바로 문의하세요.
      .contact-button-container
        = link_to new_contact_path,  class: 'btn btn-default btn-contact' do
          협업 문의하기
      .contact-envelope
        = image_tag 'contact-envelope.png'

%section.notice.d-none.d-sm-block{ style: 'margin-top: 40px; margin-bottom: 40px' }
  .container.container-sm
    .base-section-title
      공지
  .container
    .text-center{ style: 'margin-top: 40px' }
      %button.subscribe{class: 'btn btn-primary', 'data-toggle': "modal", 'data-target': "#notice-modal", style: 'height: auto; font-size: 20px;'}
        2022년 사회적협동조합 빠띠 정기총회 공고
  #notice-modal.modal.fade{class: @subscribe, :role => "dialog", :tabindex => "-1"}
    .modal-dialog.modal-lg{:role => "document"}
      .modal-content
        .modal-body
          .notice-modal-title 2022년 사회적협동조합 빠띠 정기총회 공고
          .notice-modal-description
            %p 사회적협동조합 빠띠의 정관 제 31조, 제 33조에 의거하여
            %p 다음과 같이 2022년 사회적협동조합 빠띠 정기총회를 개최하고자 합니다.
            %p 조합원과 임직원 여러분께서는 총회에 함께하여 주시기 바랍니다.
          %table.notice-modal-table
            %tr
              %td.notice-modal-label 일시
              %td.notice-modal-content 2022년 2월 23일 수요일 오후 4시
            %tr
              %td.notice-modal-label 장소
              %td.notice-modal-content
                온라인 총회 zep
                &nbsp;
                = link_to "https://zep.us/play/87e3Oy"
            %tr
              %td.notice-modal-label 빠띠 타운홀
              %td.notice-modal-content
                = link_to "https://townhall.kr/m/2411"
            %tr
              %td.notice-modal-label 총회 안건 기록
              %td.notice-modal-content
                = link_to "https://nuly.do/qS2u"
            %tr
              %td.notice-modal-label{colspan:"2"} 상정 안건
            %tr
              %td{colspan:"2"}
                .notice-modal-content-box
                  %p
                    %span.number 1
                    2021년 사회적협동조합 빠띠 사업결과 보고 승인
                  %p
                    %span.number 2
                    2021년 사회적협동조합 빠띠 결산안 승인
                  %p
                    %span.number 3
                    2022년 사회적협동조합 빠띠 사업계획 승인
                  %p
                    %span.number 4
                    2022년 사회적협동조합 빠띠 예산안 승인
                  %p
                    %span.number 5
                    감사보고서, 경영공시 자료 승인
                  %p
                    %span.number 6
                    기타 안건 : 조합 및 출자금 현황 보고, 허니문
            %tr
              %td{colspan:"2", style: "text-align: center;"}
                %p 총회 안건 기록을 살펴보시고, 2월 23일 (수)까지
                %p 빠띠 타운홀로 서면 결의를 부탁드립니다
            %tr
              %td.close-btn-wrap{colspan:"2"}
                .close-btn{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button", "aria-hidden" => "true"} 닫기

%section.activists
  .container.container-sm
    .base-section-title
      활동가 커뮤니티 참여하기
    .base-section-desc.text-keep-all
      %span.text-nowrap 빠띠 민주주의 활동가들이
      %br
      함께 교류하는
      %span.text-nowrap 커뮤니티입니다.
    .activists-button-container
      = link_to "https://democracy-activists.parti.xyz/",  class: 'btn btn-default btn-contact' do
        참여하기

%footer.app-footer
  .container-fluid
    .logo
      빠띠
    .utils
      .utils-left
        .util
          = link_to 'https://github.com/parti-coop', target: '_blank' do
            %i.fab.fa-github
        .util
          = link_to 'https://facebook.com/PartiUnion', target: '_blank' do
            %i.fab.fa-facebook
        .util
          = link_to 'https://twitter.com/parti_coop', target: '_blank' do
            %i.fab.fa-twitter
        .util
          = link_to 'https://www.instagram.com/particoop_/', target: '_blank' do
            %i.fab.fa-instagram
        .util.util-br.d-block.d-lg-none
        .util
          = link_to '문의 contact@parti.coop', 'mailto:contact@parti.coop'
        .util.util-br.d-block.d-lg-none
        .util
          = link_to '개인정보처리방침', privacy_path
        .util.util-br.d-block.d-sm-none
        .util
          = link_to '행정안전부', 'https://www.mois.go.kr/', target: '_blank'
        .util
          = link_to '부패공익신고', 'https://www.clean.go.kr/index.es?sid=a1', target: '_blank'

      .utils-right
        .democracy-report-subscribe
          = form_with url: subscribe_reports_path, class: 'form-inline js-form-validation' do |f|
            %label{ for: :email } 민주주의 리포트 구독하기
            .form-group<>
              = f.text_field :name, placeholder: '이름', id: 'site-subscribe-report-input-name', class: 'form-control', data: { 'rule-required': true, 'invalid-error': '#js-report-subscribe-error', msg: '이름과 이메일 주소는 필수 입력 항목입니다.' }
              = f.email_field :email, placeholder: '이메일 주소', id: 'site-subscribe-report-input-email', class: 'form-control', data: { 'rule-required': true, 'invalid-error': '#js-report-subscribe-error', msg: '이름과 이메일 주소는 필수 입력 항목입니다.' }
            %button.btn.btn-primary.btn-subscribe{ type: :submit } 구독신청
          #js-report-subscribe-error
    .utils
      %span
        %span.text-nowrap 사회적협동조합 빠띠
        %span.d-none.d-sm-inline= "|"
        %br.d-block.d-sm-none
        %span.text-nowrap 이사장: 권오현
        %span.d-none.d-sm-inline= "|"
        %br.d-block.d-sm-none
        %span.text-nowrap 등록번호: 278-82-00201
        %span.d-none.d-lg-inline= "|"
        %br.d-block.d-lg-none
        %span.text-nowrap 서울시 서대문구 수색로 43
        %br.d-block.d-sm-none
        %span.text-nowrap 사회적경제마을자치센터 2층
        %span.d-none.d-sm-inline= "|"
        %br.d-block.d-sm-none
        %span.text-nowrap
          Email:
          %span
          %a{href: "mailto:member@parti.coop"}> member@parti.coop
    .license.d-md-flex
      %a(href="https://creativecommons.org/licenses/by/4.0/deed.ko" target="_blank")
        = image_tag 'ccby4.png', style: 'height: 2.8em; margin-right: 0.4em;'
      .flex-fill
        %b Parti Co-op.
        에 의해 작성된
        이 웹사이트는
        %br
        %a.text-nowrap.text-underline.hover:text-underline(href="https://creativecommons.org/licenses/by/4.0/deed.ko" target="_blank") 크리에이티브 커먼즈 저작자표시 4.0 국제
        %span.text-nowrap 라이선스에 따라 이용할 수 있습니다.

app/views/application/_header.html.haml
%nav.app-nav.navbar.navbar-expand-lg.navbar-light.fixed-top.bg-white
  %a.navbar-brand{ href: root_url }
    = image_tag 'header-logo.png'
  %button.navbar-toggler(aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" data-target="#navbarCollapse" data-toggle="collapse" type="button")
    %span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    %ul.navbar-nav.mt-2.ml-lg-auto.d-lg-flex.d-sm-flex
      %li.nav-item.dropdown
        %a.nav-link.dropdown-toggle{ href: '#', id: 'header-navbar-dropdown', role: 'button', 'data-toggle': 'dropdown', 'aria-haspopup': 'true', 'aria-expanded': 'false' }
          우리가 하는 일
        .dropdown-menu{ 'aria-labelledby': 'header-navbar-dropdown' }
          - Solution::DICTIONARY.each do |_, solution_info|
            %a.dropdown-item{ href: send(solution_info[:path_text]) }
              != solution_info[:title]
      %li.nav-item
        %a.nav-link{ href: send(Platform::INFO[:path_text]) }
          민주주의 플랫폼
      %li.nav-item
        %a.nav-link{ href: camp_path }
          민주주의 캠프
      %li.nav-item
        %a.nav-link{ href: what_we_do_path } 소식
      %li.nav-item
        %a.nav-link{ href: new_contact_path } 협업 문의
      %li.nav-item
        %a.nav-link{ href: "https://secure.donus.org/parti/pay", target: "_blank" } 후원하기
    -# %form.form-inline.mt-2.mt-md-0
    -#   %input.form-control.mr-sm-2(aria-label="Search" placeholder="Search" type="text")/
    -#   %button.btn.btn-outline-success.my-2.my-sm-0(type="submit") Search