config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  get 'parti2022', to: 'pages#parti2022'
  get 'home_what_we_do', to: 'pages#home_what_we_do'
  get 'what_we_do', to: 'pages#what_we_do'
  get 'marketing', to: 'pages#marketing'
  get 'camp', to: 'pages#camp'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_revisions/v1', to: 'pages#privacy_revisions_v1', as: :privacy_revisions_v1
  Solution::DICTIONARY.each do |solution_slug,_|
    get "solutions/#{solution_slug}", to: "solutions##{solution_slug}", as: :"solutions_#{solution_slug}"
  end
  get 'solutions/soft', to: 'solutions#soft', as: :solutions_soft
  post 'reports/subscribe', to: 'pages#subscribe_reports', as: :subscribe_reports

  resources :contacts
  resources :posts, only: :show

  post 'attachments', to: 'attachments#create'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/models/solution.rb
class Solution
  # 데모스
  DEMOS_TOOLKITS = [
    {
      image_path: 'demos_solution_2.jpg',
      title: '시민참여 공론장',
      description: '''
        사회적으로 관심과 논의가 필요한 의제, 지역 또는 공동체의 일상에서 논의가 필요한 사안에 관심있는 시민 누구나 쉽게 토론에 참여할 수 있습니다.
      ''',
      url: 'https://toolkit.parti.coop/sphere/debate.html'
    },
    {
      image_path: 'demos_solution_1.png',
      title: '의제기획 및 선정',
      description: '''
        시민의 제안이나 기관의 정책 공론화 여부를 검토하고, 숙의를 통해 공적 의제로 만들어냅니다.
      ''',
      url: 'https://toolkit.parti.coop/sphere/agenda.html'
    },
    {
      image_path: 'demos_solution_3.jpg',
      title: '시민제안 워크숍',
      description: '''
        기관의 정책이나 일상의 관심사 등에 대해 시민들과 함께 토론하고 의견과 제안을 모아봅니다.
      ''',
      url: 'https://toolkit.parti.coop/sphere/workshop.html'
    },
    {
      image_path: 'demos_solution_5.png',
      title: '시민제안 실험장',
      description: '''
        시민의 제안을 바탕으로 가상의 환경을 만들어 직접 실험해보고 그 결과를 바탕으로 공론화 하는 실험장입니다.
        <br><br>
        이를 통해 제안의 실효성과 정책화의 걸림돌, 해결방안을 검증합니다.
      ''',
      url: 'https://toolkit.parti.coop/sphere/citizenlab.html'
    },
    {
      image_path: 'demos_solution_4.jpg',
      title: '찾아가는 시민제안',
      description: '''
        더 많은 시민들에게 시민참여플랫폼을 직접 경험할 수 있도록 다양한 이벤트를 기획합니다.
        <br><br>
        주요 이슈에 대한 현장 시민의견 수렴, 시민참여플랫폼 브랜드  홍보 등을 진행합니다.
      ''',
      url: 'https://toolkit.parti.coop/sphere/suggestion.html'
    },
    {
      image_path: 'demos_solution_6.png',
      title: '시민참여플랫폼 운영가이드 - 데모스X 운영가이드 1.1',
      description: '''
        시민제안 내 의제를 바탕으로 공론화 진행, 기관 의제에 대한 시민 의견 수렴 공론장을 기획하고 운영하는 온, 오프라인 공론장을 만듭니다.
      ''',
      url: 'https://toolkit.parti.coop/demosx/'
    }
  ]

  DEMOS_PORTFOLIOS = [
    {
      image_path: 'demos_portfolio_1.png',
      title: '민주주의서울 기획 및 운영',
      description: '''
        서울시와 함께 공론장 및 O2O 플랫폼 기획 및 운영<br><br>
        시민과 서울시가 함께 정책을 논의하고 실행하는 시민참여플랫폼
      ''',
      url: ' https://parti.coop/posts/93'
    },
    {
      image_path: 'demos_portfolio_2.png',
      title: '김해문화재단 김해가야G',
      description: '''
        김해문화재단과 함께 공유공간 커뮤니티 빌딩 사업 기획 및 운영<br><br>
        시민이 직접 공유공간 활용 방안을 제안하고 운영해보는 커뮤니티 실험
      ''',
      url: 'https://parti.coop/posts/5'
    },
    {
      image_path: '',
      title: '대전NGO지원센터 워크숍',
      description: '''
        대전 활동가들과 함께한 일상의 공론장 만들기<br><br>
        시민 누구나 일상의 공론장을 열 수 있고, 함께 대화하며 나와 다른이의 목소리를 듣고 자신의 이야기를 구체화해가는 전반의 과정을 경험하는 워크숍
      ''',
      url: 'https://parti.coop/posts/151'
    },
    {
      image_path: '',
      title: 'TBS 오픈테이블',
      description: '''
        시민의 방송은 어떤 이야기를 담아내야 할까?<br><br>
        더 많은 이들의 참여로 시민이 주체가 되는 방송을 만들고자, 시민들에게 방송 기획안을 공모받아 실제 방송으로 만드는 프로젝트
      ''',
      url: 'https://parti.coop/posts/146'
    }
  ]

  ORG_TOOLKITS = [
    {
      image_path: 'org_solution_1.jpg',
      title: '소셜이슈 커뮤니티 101',
      description: '''
        사회 이슈에 대해 다양한 사람이 모여 안전하고 개방적으로 이야기 나누고 할 수 있는 만큼 협력하는 커뮤니티를 만들 때 활용할 수 있는 가이드입니다.
      ''',
      url: 'https://toolkit.parti.coop/community/community101'
    },
    {
      image_path: 'org_solution_2.jpg',
      title: '항해하는 조직 101',
      description: '''
        일상 중 가장 많은 시간을 보내는 조직 안에서 더 민주적으로 의사소통할 수 있는 방법들을 소개합니다.
      ''',
      url: 'https://toolkit.parti.coop/community/org101.html'
    },
    {
      image_path: 'org_solution_3.jpg',
      title: 'DIY 정당 101',
      description: '''
        우리에게 꼭 필요한 문제나 관심사를 다루는 프로젝트 정당을 직접 만듭니다.
      ''',
      url: 'https://toolkit.parti.coop/community/diy-party101.html'
    }
  ]

  ORG_PORTFOLIOS = [
    {
      image_path: 'org_portfolio_1.jpg',
      title: '버터나이프크루',
      description: '''
        성평등 정책을 만드는 청년 커뮤니티
      ''',
      url: 'https://parti.coop/posts/148'
    },
    {
      image_path: 'org_portfolio_5.jpg',
      title: '커먼즈필드제주',
      description: '''
        삶의 전환을 실험하는 시민 커뮤니티
      ''',
      url: 'https://parti.coop/posts/158'
    },
    {
      image_path: 'org_portfolio_2.jpg',
      title: '나는알아야겠당',
      description: '''
        국내 최초 이슈 프로젝트 정당
      ''',
      url: 'https://parti.coop/posts/165'
    },
    {
      image_path: 'org_portfolio_6.png',
      title: '일인당',
      description: '''
        일인가구 공동공간을 만드는 지역 이슈 커뮤니티
      ''',
      url: 'https://alone.parti.xyz/'
    },
  ]

  TOWNHALL_TOOLKITS = [
    {
      image_path: 'townhall_toolkit_1.jpg',
      title: '아이디어 마켓',
      description: '''
        수많은 아이디어 중에서 우선순위를 정하는 일에 구성원 모두가 참여하여 결정합니다.
      ''',
      url: 'https://toolkit.parti.coop/'
    },
    {
      image_path: 'townhall_toolkit_2.jpg',
      title: '열린 토론회',
      description: '''
        특정이슈와 관련된 서로의 의사를 공유하고 숙의를 거쳐 의미 있는 의사결정을 도출합니다.
      ''',
      url: 'https://toolkit.parti.coop/ '
    }
  ]

  TOWNHALL_PORTFOLIOS = [
    {
      image_path: 'townhall_portfolio_1.png',
      title: '2021 구로구에 필요한 정책을 논하는 시민 참여단',
      description: '''
        구로구청, 구로구민과 함께 2021년도 구로구 지역사회혁신계획 수립을 위한 시민 총회 개최
      ''',
      url: 'https://blog.naver.com/digital9ro/222005700481'
    },
    {
      image_path: 'townhall_portfolio_2.jpg',
      title: '저출산고령화 굿 아이디어 공모전',
      description: '''
        제4차 저출산고령사회 기본 계획을 위한 좋은 아이디어 6개 선정
      ''',
      url: 'https://parti.coop/posts/182'
    },
    {
      image_path: 'townhall_portfolio_3.jpg',
      title: '2019 코리아 챌린지',
      description: '''
        국민이 주도하는 대한민국 미래 100년을 준비하기 위해 국민참여 아이디어 경진대회 개최
      ''',
      url: 'http://www.korea.kr/news/policyNewsView.do?newsId=148862989'
    },
    {
      image_path: 'townhall_portfolio_4.png',
      title: '2018 실패박람회',
      description: '''
        48개의 주요 실패 이슈를 공유하고 토론에서 ‘빠띠 타운홀’을 활용해 토론을 진행
      ''',
      url: 'https://democracy-activists.parti.xyz/posts/28650'
    },
  ]

  CAMPAIGN_TOOLKITS = [
    {
      image_path: 'cam_solution_1.png',
      title: '캠페이너 인생게임',
      description: '''
        짧은 시간에 캠페인 전 과정을 실행하면서 캠페이너에게 필요한 기술과 태도를 알게 됩니다.
      ''',
      url: 'https://toolkit.parti.coop/campaign/campaigner.html'
    },
    {
      image_path: 'cam_solution_2.png',
      title: '캠페인 101',
      description: '''
        다양한 시민의 참여를 모으고, 촉구 대상에게 답변을 요구하는 캠페인을 만드는 방법을 소개합니다.
      ''',
      url: 'https://toolkit.parti.coop/campaign/campaign101.html'
    }
  ]

  CAMPAIGN_PORTFOLIOS = [
    {
      image_path: 'cam_portfolio_1.png',
      title: '차별잇수다',
      description: '''
      차별금지법제정연대와 차별금지법 제정을 위한 서명을 모으고 차별에 맞서기 위한 경험을 기록
      ''',
      url: 'https://campaigns.kr/campaigns/192'
    },
    {
      image_path: 'cam_portfolio_5.jpg',
      title: '카페 일회용컵 줄이기',
      description: '''
      28개 커피숍과 환경부가 1회용  플라스틱 제품에 대해 대책을 마련하도록 촉구하는 캠페인
      ''',
      url: 'https://campaigns.kr/campaigns/79'
    },
    {
      image_path: 'cam_portfolio_2.png',
      title: '미래에서 온 투표',
      description: '''
      청소년들의 제안을 모아 아동정책을 제19대 대선 후보에게 전달하는 정책 제안 프로젝트
      ''',
      url: 'http://votefuture.kr'
    },
    {
      image_path: 'cam_portfolio_4.png',
      title: '아청법 개정 촉구',
      description: '''
      아동청소년 성매수 피해자를 피해자로 인정하기 위한 아청법 개정을 촉구하는 캠페인
      ''',
      url: 'https://campaigns.kr/campaigns/68'
    },
    {
      image_path: 'cam_portfolio_6.png',
      title: '#우리에겐 페미니스트 선생님이 필요합니다',
      description: '''
      성평등 교육 보장을 촉구하고, 개인에게 가해지는 사이버불링을 멈추기 위한 기자회견 연명 캠페인
      ''',
      url: 'https://campaigns.kr/campaigns/54'
    },
    {
      image_path: 'cam_portfolio_7.png',
      title: '아름다운재단 나눔교육 청소년과 함께한 <캠페이너 인생게임> 워크숍',
      description: '''
      아름다운재단의 나눔교육 청소년 100명과 함께한 시민주도 캠페인 디자인 워크숍
      ''',
      url: 'https://parti.coop/posts/89'
    }
  ]

  DATA_TOOLKITS = []

  DATA_PORTFOLIOS = [
    {
      image_path: 'data_portfolio_1.jpg',
      title: '코로나19 공공데이터 공동대응',
      description: '코로나19 공공데이터에 관해 누구나 기여할 수 있는 크라우드 소싱 작업',
      url: 'http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=001&oid=030&aid=0002871900'
    },
    {
      image_path: 'data_portfolio_2.png',
      title: '세월호아카이브',
      description: '세월호 참사의 기록에 시민과 연구자가 자유롭게 접근할 수 있는 세월호 아카이브',
      url: 'https://sewolarchive.org/'
    },
    {
      image_path: 'cam_portfolio_3.png',
      title: '당신의 투표를 예측해 드립니다',
      description: '''
      전국 유권자 1500명에게 물어, 최적화된 7개 문항만을 뽑아 구성한 예측모델로 응답자의 투표 결과를 예측한 프로젝트
      ''',
      url: 'https://toolkit.parti.coop/lab.html#%EB%8B%B9%EC%8B%A0%EC%9D%98-%ED%88%AC%ED%91%9C%EB%A5%BC-%EC%98%88%EC%B8%A1%ED%95%B4-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4'
    }
  ]

  LAB_TOOLKITS = []

  LAB_PORTFOLIOS = [
    {
      image_path: 'campaign-issuebattle.png',
      title: '​정책배틀',
      description: '''
      사회적 의제를 놓고 전문가, 활동가, 정치인, 일반 시민들이 모여서 토론과 투표를 통해 해결책을 마련해 가는 참여형 의사결정 플랫폼 "타운홀"을 활용하여 오프라인에서 전문가가 제안하고 시민이 투표하는 "정책배틀" 캠페인.
      ''',
      url: 'https://union.parti.xyz/posts/15092'
    },
    {
      image_path: 'campaign-inno.png',
      title: '​당신은 혁신의 편입니까?',
      description: '''
      혁신가들의 제안으로 만드는 혁신정책 프로젝트
      ''',
      links: [
        {
          link: 'http://fcinst.org/reviews/27',
          title: '혁신가 100명이 정책을 제안하고 대선캠프가 답하다​'
        }
      ],
      url: 'https://democracy-activists.parti.xyz/posts/15089'
    },
    {
      image_path: 'campaign-go.png',
      title: '​우주당: 하야GO​',
      description: '''
      직접민주주의 프로젝트 정당 우주당의 첫번째 이번트로, 박근혜 대통령 탄핵 집회 참여 인증사진과 메시지를 공유하여 집회에 같이 참여한 참가자를 찾거나 장소에 구애받지 않고 온라인에서 함께할 수 있는 프로젝트.
      ''',
      links: [
        {
          link: 'http://www.hankookilbo.com/v/ca1a3bb84d5749f789d20884b01956f3%20http://www.ohmynews.com/NWS_Web/view/at_pg.aspx?CNTN_CD=A0002272275',
          title: '순실길 밟기·하야GO…뭐라도 하고픈 당신을 위한 5가지 시위법​'
        }
      ],
      url: 'https://wouldyouparty.campaigns.kr/campaigns/136/pickets'
    },
    {
      image_path: 'campaign-iknow.png',
      title: '​나는 알아야겠당​',
      description: '''
      바글시민와글입법 3차까지의 진행을 이어 법안 심사 통과 압박 액션까지, 총 800여명의 당원이 뭉친 국내 최초의 프로젝트 정당.
      <br><br>

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  Solution::DICTIONARY.each do |solution_slug, solution_info|
    define_method(solution_slug) do
      @slug = solution_slug
      @info = solution_info

      prepare_meta_tags(title: @info[:title], description: @info[:seo_desc], url: send(:"solutions_#{@slug}_url"))
    end
  end

  def soft
    @slug = Platform::INFO[:slug]
    @info = Platform::INFO

    prepare_meta_tags(title: @info[:title], description: @info[:seo_desc], url: send(:"solutions_soft_url"))
  end
end

app/views/solutions/_show.html.haml
%section.base-key-visual
  .base-line
    .container
      .base-title-container
        .base-page-subtitle
          != info[:subtitle]
        .base-page-title
          != info[:title]

= content

- if info[:portfolios]&.any?
  %section.tiles.tiles-portfolio
    .tiles-title-line
      .container
        .tiles-title
          포트폴리오
          - if slug == :org
            .lead.text-dark 우리는 더 많은 사람들이 관심과 이슈로 만나 협력할 때 더 민주적인 세상이 된다고 믿습니다.
    .container
      .tiles-container<>
        - info[:portfolios].each do |portfolio|
          .tile-container<>
            .tile
              = link_to (portfolio[:url].presence || new_contact_path) , target: '_blank' do
                .tile-cover-container
                  .tile-cover{ style: (portfolio[:image_path].present? ? "background-image: url(#{asset_url("solutions/#{slug}/#{portfolio[:image_path]}")})" : "background-image: url(#{asset_url("#{slug}-key-visual.png")})") }
                .tile-meta
                  .title
                    != portfolio[:title]
                  .body
                    != portfolio[:description]
              - if portfolio[:links]&.any?
                .tile-links
                  %div 관련 뉴스&middot;링크
                  %ul.list-unstyled
                    - portfolio[:links].each do |link|
                      %li
                        %a{ href: link[:url], target: '_blank' }
                          \-
                          = link[:title]


- if info[:items].any?
  %section.tiles.tiles-portfolio
    .tiles-title-line
      .container
        .tiles-title
          != info[:items_name]
    .container
      .tiles-container{ class: "tiles-container-#{slug}" }<>
        - info[:items].each do |item|
          .tile-container<>
            %a.anchor(id="anchor-item-#{item[:slug]}")
            = link_to (item[:url].presence || new_contact_path) , target: '_blank' do
              .tile
                .tile-cover-container
                  .tile-cover{ style: (item[:image_path].present? ? "background-image: url(#{asset_url("solutions/#{slug}/#{item[:image_path]}")})" : "background-image: url(#{asset_url('samples/home/whatwedo/card1.png')})") }
                .tile-meta
                  .title
                    != item[:title]
                  .body.text-keep-all
                    != item[:description]

- if info[:using_platform_slugs]&.any?
  %section.tiles.tiles-portfolio
    .tiles-title-line
      .container
        .tiles-title
          플랫폼
    .container
      .tiles-container.tiles-container-soft<>
        - info[:using_platform_slugs].each do |using_platform_slug|
          - using_platform = Platform::DICTIONARY[using_platform_slug]
          .tile-container<>
            = link_to (using_platform[:url].presence || new_contact_path) , target: '_blank' do
              .tile
                .tile-cover-container
                  .tile-cover{ style: (using_platform[:image_path].present? ? "background-image: url(#{asset_url("solutions/soft/#{using_platform[:image_path]}")})" : "background-image: url(#{asset_url('samples/home/whatwedo/card1.png')})") }
                .tile-meta
                  .title
                    != using_platform[:title]
                  .body.text-keep-all
                    != using_platform[:description]
%section.tiles.tiles-what-we-do
  .tiles-title-line
    .container
      .tiles-title.text-keep-all
        소식
  .container.container-full
    .tiles-container
      - Post.published.recent.by_category_slug(slug).limit(3).each do |post|
        .tile-container<>
          = link_to post_path(id: post.id) do
            .tile
              .tile-meta
                .title!= post.title
                .created-at= static_day_f post.published_at
      .tile-container<>
        = link_to what_we_do_path(category_slug: slug), class: 'tile tile-more' do
          .more-link
            #{ slug == :soft ? '소식 더 보기' : '하는 일 더 보기' }
          .more-icon
            %i.fas.fa-arrow-right

app/views/solutions/campaign.html.haml
- content = capture do
  %section.descriptions
    .container
      %p.lead.text-keep-all
        시민 누구나
        %br
        %span.text-nowrap 캠페인을 하는 세상을
        만듭니다.

  %section.tiles.tiles-with
    .tiles-title-line
      .container
        .tiles-title
          함께하는 일
    .container
      .tiles-container<>
        .tile
          .tile-meta
            .title
              캠페인 기획과 협업
            .body.text-keep-all
              시민주도 캠페인을 발굴하고, 파트너들과 함께 다양한 방식의 캠페인을 합니다.
        .tile
          .tile-meta
            .title
              캠페인 교육 워크숍
            .body.text-keep-all
              누구나 시민주도 캠페인을 쉽게 할 수 있도록 하는 교육과 워크숍을 제공합니다.
= render 'solutions/show', slug: @slug, info: @info, content: content

app/views/solutions/data.html.haml
- content = capture do
  %section.descriptions
    .container
      %p.lead.text-keep-all
        데이터로 더 투명하고
        %br
        신뢰하는 사회를 만듭니다.

  %section.tiles.tiles-with
    .tiles-title-line
      .container
        .tiles-title
          함께하는 일
    .container
      .tiles-container<>
        .tile
          .tile-meta
            .title
              공익데이터 포럼
            .body.text-keep-all
              공익데이터 및 공공데이터에 대한 정책 연구와 제안을 합니다.
        .tile
          .tile-meta
            %a.title(href="https://datapublic.kr/" target="_blank")
              데이터 퍼블릭
            .body.text-keep-all
              사회적 이슈의 원본 데이터를 모으고, 이를 활용해 사실 관계를 확인합니다.
              %br
              %a(href= "https://datapublic.kr/" target="_blank" class="text-primary")
                바로가기
                %i.fa.fa-arrow-right

= render 'solutions/show', slug: @slug, info: @info, content: content

app/views/solutions/demos.html.haml
- content = capture do
  %section.descriptions
    .container
      %p.lead.text-keep-all
        이해관계자들이
        %span.text-nowrap 더 많이 소통하고
        %br
        협력하는 공론장을 만듭니다.

  %section.tiles.tiles-with
    .tiles-title-line
      .container
        .tiles-title
          함께하는 일
    .container
      .tiles-container<>
        .tile
          .tile-meta
            .title
              공론장&middot;시민참여 플랫폼
            .body.text-keep-all
              다양한 이해관계자가 참여하는 협력적 공론장을 만듭니다.
              %br
              기관과 조직의 시민참여플랫폼을 기획하고 운영합니다.
              %br
              온라인과 오프라인을 연계한, 크고 작은 공론장을 만듭니다.
        .tile
          .tile-meta
            .title
              교육 및 워크숍
            .body.text-keep-all
              공론장 툴킷과 플랫폼을 바탕으로 다양한 워크숍과 교육을 기획하고 운영합니다.
        .tile
          .tile-meta
            .title
              컨설팅&middot;자문
            .body.text-keep-all
              공론장이나 시민참여플랫폼을 운영하는 기관과 조직을 대상으로 컨설팅 및 자문을 제공합니다.
        .tile
          .tile-meta
            .title
              네트워크
            .body.text-keep-all
              더 나은 세상을 만드는 다양한 커뮤니티 활동가들을 연결합니다.
              %br
              %a(href= "https://democracy-activists.parti.xyz/p/public-sphere" target="_blank" class="text-primary")
                공론장 활동가 네트워크 참여하기
                %i.fa.fa-arrow-right
= render 'solutions/show', slug: @slug, info: @info, content: content

app/views/solutions/lab.html.haml
- content = capture do
  %section.descriptions
    .container
      %p.lead.text-keep-all
        다양한 실험을 통해
        %br
        더 민주적인 세상을 만듭니다.

= render 'solutions/show', slug: @slug, info: @info, content: content

app/views/solutions/org.html.haml
- content = capture do
  %section.descriptions
    .container
      %p.lead.text-keep-all
        시민, 조직과 함께
        %br
        더 민주적이고 협력적인 커뮤니티를 만듭니다.

  %section.tiles.tiles-with
    .tiles-title-line
      .container
        .tiles-title
          함께하는 일
    .container
      .tiles-container<>
        .tile
          .tile-meta
            .title
              협력 프로젝트
              .text-muted Collaborate
            .body.text-keep-all
              %p
                지속가능하고 협력적인 커뮤니티를 만드는 일에 관심이 있으신가요?
              %p
                빠띠의 노하우가 담긴 툴킷과 디지털 플랫폼을 기반으로 협력적 커뮤니티를 함께 만들 수 있습니다. 초기 아이디어 단계여도 좋습니다. 마음껏 프로젝트를 제안해주세요.
        .tile
          .tile-meta
            .title
              교육 및 워크숍
              .text-muted Inspire
            .body.text-keep-all
              협력적 커뮤니티를 직접 디자인하고, 경험해볼 수 있는 워크숍을 진행합니다.
              %br
              빠띠의 워크숍은 이론이나 기술을 배우기보다 스스로 실행하며 배우는 참여형 워크숍입니다. 규모와 환경에 따라 다 회차 커리큘럼 프로그램도 가능합니다.
        .tile
          .tile-meta
            .title
              네트워크
              .text-muted Connect
            .body.text-keep-all
              더 나은 세상을 만드는 다양한 커뮤니티 활동가들을 연결합니다.
              %br
              커뮤니티를 조직하고 운영하는 것에 관심있는 사람들을 만나 경험과 영감을 나눠보세요.
              %br
              %a(href= "https://democracy-activists.parti.xyz/p/community" target="_blank" class="text-primary")
                커뮤니티 활동가 네트워크 참여하기
                %i.fa.fa-arrow-right

= render 'solutions/show', slug: @slug, info: @info, content: content

app/views/solutions/soft.html.haml
- content = capture do
  %section.descriptions
    .container
      %p.lead.text-keep-all
        일상과 세상을
        %br
        더 민주적으로 만드는 빠띠의 플랫폼

= render 'solutions/show', slug: @slug, info: @info, content: content

app/views/solutions/townhall.html.haml
- content = capture do
  %section.descriptions
    .container
      %p.lead.text-keep-all
        모두가 쉽게 자신의 의견을 나누고
        %br
        의사결정할 수 있는 공간을 만듭니다.

  %section.tiles.tiles-with
    .tiles-title-line
      .container
        .tiles-title
          함께하는 일
    .container
      .tiles-container<>
        .tile
          .tile-meta
            .title
              협력 프로젝트
              .text-muted Collaborate
            .body.text-keep-all
              %p
                디지털 플랫폼과 빠띠의 노하우가 담긴 툴킷을 기반으로 함께 프로젝트 기획 및 운영을 할 수 있습니다.
                %br
                초기 아이디어 단계여도 좋습니다. 마음껏 프로젝트를 제안해주세요.
        .tile
          .tile-meta
            .title
              컨설팅 및 자문
              .text-muted Consulting
            .body.text-keep-all
              온오프라인 통합, 비대면 모임과 행사를 기획하고 운영하는 기관, 조직을 대상으로 컨설팅 및 자문을 제공합니다.
        .tile
          .tile-meta
            .title
              교육 및 워크숍
              .text-muted Inspire
            .body.text-keep-all
              %p
                의사결정 방식을 직접 설계하고 다양한 사례를 빠띠의 워크숍은 이론이나 기술을 배우기보다 스스로 실행하며 배우는 참여형 워크숍입니다.
                %br
                규모와 환경에 따라 다 회차 커리큘럼 프로그램도 가능합니다.

= render 'solutions/show', slug: @slug, info: @info, content: content